In [2]:
import pandas as pd
import numpy as np
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import plotly
plotly.__version__
import plotly
from plotly.graph_objs import Scatter, Layout
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
# Scientific libraries
from numpy import arange,array,ones
from scipy import stats
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

/Library/anaconda/lib/python2.7/site-packages/pandas/computation/__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)

In [2]:
train=pd.read_csv("train_ireg_amd_dmd.csv")
train['index']=train['Unnamed: 0']
del train['Unnamed: 0']

In [3]:
train.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,index
0,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0,0
1,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0,1
2,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0,2
3,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0,3
4,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0,4

In [ ]:
train['NumberOfTime30-59DaysPastDueNotWorse']=

In [4]:
train.describe()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,index
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.500000e+05,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,0.066840,6.048438,52.295553,0.421033,353.005076,6.687979e+03,8.452760,0.265973,1.018240,0.240387,0.763573,74999.500000
std,0.249746,249.755371,14.771249,4.192781,2037.818523,1.291607e+04,5.145951,4.169304,1.129771,4.155179,1.101086,43301.414527
min,0.000000,0.000000,21.000000,0.000000,0.000000,-2.147359e+04,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.029867,41.000000,0.000000,0.175074,3.772000e+03,5.000000,0.000000,0.000000,0.000000,0.000000,37499.750000
50%,0.000000,0.154181,52.000000,0.000000,0.366508,5.889000e+03,8.000000,0.000000,1.000000,0.000000,0.000000,74999.500000
75%,0.000000,0.559046,63.000000,0.000000,0.868254,8.061000e+03,11.000000,0.000000,2.000000,0.000000,1.000000,112499.250000
max,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000,149999.000000

In [72]:
train_discretized=pd.read_csv('train_ireg_amd_dmd_discretized.csv')
train_discretized['index']=train_discretized['Unnamed: 0']
del train_discretized['Unnamed: 0']

In [6]:
from pandasql import sqldf

In [88]:
test=pd.read_csv('pred_xgb_record.csv')
test.head()

,index,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,prob
0,1,NaN,0.885519,43,0,0.177513,5700.0,4,0,0,0,0.0,0.070073
1,2,NaN,0.463295,57,0,0.527237,9141.0,15,0,4,0,2.0,0.055193
2,3,NaN,0.043275,59,0,0.687648,5083.0,12,0,1,0,2.0,0.031300
3,4,NaN,0.280308,38,1,0.925961,3200.0,7,0,2,0,0.0,0.083172
4,5,NaN,1.000000,27,0,0.019917,3865.0,4,0,0,0,1.0,0.095478

In [109]:
test=pd.read_csv('pred_xgb_record.csv')
test.head()
test['dlq']=pd.DataFrame(np.ones(test.size))
test.loc[(test['prob']<=0.5), 'dlq'] = int(0)
test[test['dlq']==1]
groupByDependents=test.groupby(['NumberOfDependents', 'dlq']).count()

groupByDependents['index'][:,1]
numberofdependents_dlq=groupByDependents['index'][:,1]/(groupByDependents['index'][:,0] + groupByDependents['index'][:,1])
pd.DataFrame(numberofdependents_dlq)
numberofdependents_dlq=numberofdependents_dlq.dropna()

Xrange=np.arange(0,groupByDependents['age'][:,1].count())

Y=numberofdependents_dlq.as_matrix()
X=Xrange

print Y
d = {'dep_no': X, 'per': Y}
dfoutput=pd.DataFrame(d)
dfoutput.to_csv('dep_per.csv')

[ 0.01340885  0.01798064  0.02225899  0.03065076  0.0406015   0.03231939
  0.072       0.02      ]

In [211]:
test=pd.read_csv('pred_xgb_record.csv')
a=test.describe()
a=a.T
a.to_csv('forboxplot.csv')

In [4]:
#test[test['prob']<=0.5]


#np.zeros(test.size)

test['dlq']=pd.DataFrame(np.ones(test.size))

In [5]:
#test[test['prob']<=0.5]['dlq']

test.loc[(test['prob']<=0.5), 'dlq'] = int(0)

In [6]:
test[test['dlq']==1]

,index,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,prob,dlq
23,24,NaN,0.957442,69,2,0.666338,3041.000000,8,1,1,1,1.0,0.517759,1.0
69,70,NaN,1.000000,52,98,0.020303,2708.000000,0,98,0,98,0.0,0.647222,1.0
123,124,NaN,2.182724,49,0,497.000000,5714.088497,2,2,0,1,0.0,0.552055,1.0
166,167,NaN,49.923077,62,1,1396.000000,5713.382214,6,2,0,1,0.0,0.625771,1.0
280,281,NaN,1.066445,35,1,0.165934,2500.000000,2,3,0,0,4.0,0.620639,1.0
356,357,NaN,0.978913,28,2,675.000000,3560.019305,7,1,0,2,0.0,0.658776,1.0
404,405,NaN,1.103039,58,2,0.328350,7625.000000,13,5,1,7,1.0,0.777454,1.0
405,406,NaN,1.000000,52,0,0.436839,14375.000000,4,3,1,2,2.0,0.656278,1.0
625,626,NaN,0.759448,42,3,0.905240,4083.000000,17,1,1,0,2.0,0.569140,1.0
643,644,NaN,0.955719,55,2,0.591664,2950.000000,6,1,1,1,2.0,0.578963,1.0
653,654,NaN,1.076412,27,1,76.000000,4147.309079,4,1,0,0,1.0,0.552180,1.0
729,730,NaN,1.176823,39,1,0.590147,1907.000000,5,1,0,0,6.0,0.543116,1.0
844,845,NaN,1.130032,67,2,980.000000,5868.603066,7,1,0,3,0.0,0.658972,1.0
845,846,NaN,1.006821,36,8,0.698026,3900.000000,15,0,1,1,2.0,0.668848,1.0
893,894,NaN,0.959008,31,3,0.386005,3043.000000,5,2,0,2,1.0,0.713710,1.0
979,980,NaN,0.783350,43,5,0.287578,8967.000000,9,2,2,0,0.0,0.539289,1.0
1157,1158,NaN,1.000000,37,0,0.554189,1300.000000,4,1,0,2,3.0,0.572918,1.0
1176,1177,NaN,1.000000,25,98,0.000000,2935.000000,0,98,0,98,0.0,0.540700,1.0
1187,1188,NaN,0.974169,33,1,0.785844,550.000000,3,3,0,1,0.0,0.639562,1.0
1192,1193,NaN,1.045105,30,1,0.685997,4741.000000,12,1,0,0,2.0,0.558759,1.0
1206,1207,NaN,0.995798,41,1,0.329950,6600.000000,9,3,1,0,2.0,0.506796,1.0
1214,1215,NaN,1.000000,64,1,0.889688,2501.000000,3,8,1,1,0.0,0.691883,1.0
1233,1234,NaN,1.475083,44,2,0.615195,8120.000000,10,9,1,0,3.0,0.750486,1.0
1234,1235,NaN,0.976398,39,3,0.858886,7950.000000,9,6,2,3,2.0,0.831659,1.0
1275,1276,NaN,1.000000,58,0,1461.000000,9127.616635,6,2,0,2,3.0,0.534485,1.0
1293,1294,NaN,1.000000,59,2,0.493005,1500.000000,3,6,0,0,0.0,0.610474,1.0
1368,1369,NaN,0.911537,49,3,4.235620,3250.000000,26,0,0,1,0.0,0.566647,1.0
1418,1419,NaN,8.601990,58,1,0.230402,4400.000000,10,2,0,0,0.0,0.516352,1.0
1554,1555,NaN,1.000000,48,1,0.309463,4300.000000,2,2,0,1,0.0,0.553851,1.0
1557,1558,NaN,1.000000,46,1,0.139812,4033.000000,8,3,0,0,0.0,0.512662,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,99338,NaN,1.000000,53,1,0.405313,3500.000000,3,3,1,0,3.0,0.514214,1.0
99399,99400,NaN,1.659280,41,2,0.109918,5494.000000,4,3,0,0,1.0,0.590966,1.0
99418,99419,NaN,1.000000,31,1,0.281489,5104.000000,8,4,0,0,1.0,0.553392,1.0
99439,99440,NaN,1.000000,43,2,0.790631,3500.000000,7,3,2,0,2.0,0.641904,1.0
99533,99534,NaN,0.877714,43,3,0.642220,5153.000000,10,1,1,0,0.0,0.509406,1.0
99663,99664,NaN,1.000000,48,4,1.585334,1540.000000,5,3,3,1,0.0,0.748740,1.0
99740,99741,NaN,1.000364,31,6,0.805344,1833.000000,5,0,2,1,0.0,0.536187,1.0
99906,99907,NaN,0.787213,25,2,0.184064,3400.000000,4,2,0,2,0.0,0.633554,1.0
99924,99925,NaN,0.956806,52,1,0.584233,8891.000000,4,1,2,2,0.0,0.616157,1.0
100061,100062,NaN,1.000000,31,98,0.000000,2570.000000,0,98,0,98,1.0,0.562607,1.0
100078,100079,NaN,1.381032,36,1,0.202024,2370.000000,3,2,0,0,3.0,0.584089,1.0
100147,100148,NaN,0.690810,52,4,3.181818,1000.000000,11,7,1,1,1.0,0.689604,1.0
100163,100164,NaN,0.337625,47,5,1.239329,2740.000000,11,1,2,1,0.0,0.503586,1.0
100202,100203,NaN,1.000000,33,1,40.000000,4371.405892,1,1,0,1,1.0,0.553378,1.0
100242,100243,NaN,0.942359,44,2,0.780844,5000.000000,15,2,2,4,3.0,0.767986,1.0
100282,100283,NaN,1.000000,32,2,0.471176,3000.000000,7,1,1,3,1.0,0.642383,1.0
100317,100318,NaN,0.946789,50,3,0.498500,7000.000000,6,2,1,1,2.0,0.624652,1.0
100357,100358,NaN,0.635915,42,0,0.159447,6070.000000,4,5,0,2,3.0,0.605384,1.0
100418,100419,NaN,1.057295,37,2,1.346827,2000.000000,7,0,1,1,0.0,0.513072,1.0
100483,100484,NaN,0.774461,41,2,0.918214,5061.000000,11,1,3,0,1.0,0.523821,1.0
100532,100533,NaN,1.013598,50,2,0.433930,5198.000000,6,1,1,0,0.0,0.538742,1.0
100560,100561,NaN,0.962025,31,0,1.071853,1850.000000,5,1,1,1,1.0,0.507860,1.0
100569,100570,NaN,1.684631,54,0,0.165727,3191.000000,2,2,0,1,1.0,0.535142,1.0
100869,100870,NaN,1.004933,44,1,0.390652,4000.000000,6,2,0,0,4.0,0.529771,1.0
100892,100893,NaN,1.000000,39,0,0.130478,6000.000000,2,5,0,1,1.0,0.592904,1.0
101033,101034,NaN,0.676524,48,3,0.490448,5600.000000,7,3,3,2,0.0,0.679862,1.0
101207,101208,NaN,1.000000,42,98,12.000000,-5495.995601,0,98,0,98,0.0,0.707371,1.0
101283,101284,NaN,1.117520,51,5,0.807154,4500.000000,9,2,2,1,1.0,0.766672,1.0
101423,101424,NaN,0.798160,38,0,0.526438,5162.000000,8,3,2,1,2.0,0.545310,1.0
101482,101483,NaN,1.000000,33,98,0.000000,2000.000000,0,98,0,98,3.0,0.550186,1.0

In [49]:
groupByDependents=test.groupby(['NumberOfDependents', 'dlq']).count()

In [50]:
groupByDependents

                        index  SeriousDlqin2yrs  \
NumberOfDependents dlq
0.0                0.0  57832                 0
                   1.0    786                 0
1.0                0.0  19880                 0
                   1.0    364                 0
2.0                0.0  13002                 0
                   1.0    296                 0
3.0                0.0   6420                 0
                   1.0    203                 0
4.0                0.0   1914                 0
                   1.0     81                 0
5.0                0.0    509                 0
                   1.0     17                 0
6.0                0.0    116                 0
                   1.0      9                 0
7.0                0.0     49                 0
                   1.0      1                 0
8.0                0.0     16                 0
9.0                0.0      3                 0
10.0               0.0      3                 0
20.0               0.0      1                 0
43.0               0.0      1                 0

                        RevolvingUtilizationOfUnsecuredLines    age  \
NumberOfDependents dlq
0.0                0.0                                 57832  57832
                   1.0                                   786    786
1.0                0.0                                 19880  19880
                   1.0                                   364    364
2.0                0.0                                 13002  13002
                   1.0                                   296    296
3.0                0.0                                  6420   6420
                   1.0                                   203    203
4.0                0.0                                  1914   1914
                   1.0                                    81     81
5.0                0.0                                   509    509
                   1.0                                    17     17
6.0                0.0                                   116    116
                   1.0                                     9      9
7.0                0.0                                    49     49
                   1.0                                     1      1
8.0                0.0                                    16     16
9.0                0.0                                     3      3
10.0               0.0                                     3      3
20.0               0.0                                     1      1
43.0               0.0                                     1      1

                        NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  \
NumberOfDependents dlq
0.0                0.0                                 57832      57832
                   1.0                                   786        786
1.0                0.0                                 19880      19880
                   1.0                                   364        364
2.0                0.0                                 13002      13002
                   1.0                                   296        296
3.0                0.0                                  6420       6420
                   1.0                                   203        203
4.0                0.0                                  1914       1914
                   1.0                                    81         81
5.0                0.0                                   509        509
                   1.0                                    17         17
6.0                0.0                                   116        116
                   1.0                                     9          9
7.0                0.0                                    49         49
                   1.0                                     1          1
8.0                0.0                                    16         16
9.0                0.0                                     3          3
10.0               0.0                                     3          3
20.0               0.0                                     1          1
43.0               0.0                                     1          1

                        MonthlyIncome  NumberOfOpenCreditLinesAndLoans  \
NumberOfDependents dlq
0.0                0.0          57832                            57832
                   1.0            786                              786
1.0                0.0          19880                            19880
                   1.0            364                              364
2.0                0.0          13002                            13002
                   1.0            296                              296
3.0                0.0           6420                             6420
                   1.0            203                              203
4.0                0.0           1914                             1914
                   1.0             81                               81
5.0                0.0            509                              509
                   1.0             17                               17
6.0                0.0            116                              116
                   1.0              9                                9
7.0                0.0             49                               49
                   1.0              1                                1
8.0                0.0             16                               16
9.0                0.0              3                                3
10.0               0.0              3                                3
20.0               0.0              1                                1
43.0               0.0              1                                1

                        NumberOfTimes90DaysLate  NumberRealEstateLoansOrLines  \
NumberOfDependents dlq
0.0                0.0                    57832                         57832
                   1.0                      786                           786
1.0                0.0                    19880                         19880
                   1.0                      364                           364
2.0                0.0                    13002                         13002
                   1.0                      296                           296
3.0                0.0                     6420                          6420
                   1.0                      203                           203
4.0                0.0                     1914                          1914
                   1.0                       81                            81
5.0                0.0                      509                           509
                   1.0                       17                            17
6.0                0.0                      116                           116
                   1.0                        9                             9
7.0                0.0                       49                            49
                   1.0                        1                             1
8.0                0.0                       16                            16
9.0                0.0                        3                             3
10.0               0.0                        3                             3
20.0               0.0                        1                             1
43.0               0.0                        1                             1

                        NumberOfTime60-89DaysPastDueNotWorse   prob
NumberOfDependents dlq
0.0                0.0                                 57832  57832
                   1.0                                   786    786
1.0                0.0                                 19880  19880
                   1.0                                   364    364
2.0                0.0                                 13002  13002
                   1.0                                   296    296
3.0                0.0                                  6420   6420
                   1.0                                   203    203
4.0                0.0                                  1914   1914
                   1.0                                    81     81
5.0                0.0                                   509    509
                   1.0                                    17     17
6.0                0.0                                   116    116
                   1.0                                     9      9
7.0                0.0                                    49     49
                   1.0                                     1      1
8.0                0.0                                    16     16
9.0                0.0                                     3      3
10.0               0.0                                     3      3
20.0               0.0                                     1      1
43.0               0.0                                     1      1

In [51]:
#groupByDependents['age'][0]/groupByDependents['age'][0].sum()
groupByDependents['index'][:,1]
numberofdependents_dlq=groupByDependents['index'][:,1]/(groupByDependents['index'][:,0] + groupByDependents['index'][:,1])

In [52]:
pd.DataFrame(numberofdependents_dlq)

                       index
NumberOfDependents
0.0                 0.013409
1.0                 0.017981
2.0                 0.022259
3.0                 0.030651
4.0                 0.040602
5.0                 0.032319
6.0                 0.072000
7.0                 0.020000
8.0                      NaN
9.0                      NaN
10.0                     NaN
20.0                     NaN
43.0                     NaN

In [53]:
numberofdependents_dlq=numberofdependents_dlq.dropna()

Xrange=np.arange(0,groupByDependents['age'][:,1].count())

Y=numberofdependents_dlq.as_matrix()
X=Xrange

print Y

[ 0.01340885  0.01798064  0.02225899  0.03065076  0.0406015   0.03231939
  0.072       0.02      ]

In [54]:
print X
print Y

[0 1 2 3 4 5 6 7]
[ 0.01340885  0.01798064  0.02225899  0.03065076  0.0406015   0.03231939
  0.072       0.02      ]

In [58]:
d = {'dep_no': X, 'per': Y}
dfoutput=pd.DataFrame(d)
dfoutput.to_csv('dep_per.csv')

In [7]:
train_discretized.head()

,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,index
0,1,0.766127,40s,2,0.802982,10K,13,0,6,0,2.0,0
1,0,0.957151,40s,0,0.121876,5K,4,0,0,0,1.0,1
2,0,0.658180,30s,1,0.085113,5K,2,1,0,0,0.0,2
3,0,0.233810,30s,0,0.036050,5K,5,0,0,0,0.0,3
4,0,0.907239,40s,1,0.024926,20K,7,0,1,0,0.0,4

In [ ]:
numberofdependents_dlq=groupByDependents['index'][:,1]/(groupByDependents['index'][:,0] + groupByDependents['index'][:,1])

In [8]:
groupByDependents=train_discretized.groupby(['NumberOfDependents', 'SeriousDlqin2yrs']).count()

In [9]:
groupByDependents

                                     RevolvingUtilizationOfUnsecuredLines  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                                                81807
                   1                                                 5095
1.0                0                                                28126
                   1                                                 2114
2.0                0                                                17938
                   1                                                 1584
3.0                0                                                 8646
                   1                                                  837
4.0                0                                                 2565
                   1                                                  297
5.0                0                                                  678
                   1                                                   68
6.0                0                                                  134
                   1                                                   24
7.0                0                                                   46
                   1                                                    5
8.0                0                                                   22
                   1                                                    2
9.0                0                                                    5
10.0               0                                                    5
13.0               0                                                    1
20.0               0                                                    1

                                       age  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                 81807
                   1                  5095
1.0                0                 28126
                   1                  2114
2.0                0                 17938
                   1                  1584
3.0                0                  8646
                   1                   837
4.0                0                  2565
                   1                   297
5.0                0                   678
                   1                    68
6.0                0                   134
                   1                    24
7.0                0                    46
                   1                     5
8.0                0                    22
                   1                     2
9.0                0                     5
10.0               0                     5
13.0               0                     1
20.0               0                     1

                                     NumberOfTime30-59DaysPastDueNotWorse  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                                                81807
                   1                                                 5095
1.0                0                                                28126
                   1                                                 2114
2.0                0                                                17938
                   1                                                 1584
3.0                0                                                 8646
                   1                                                  837
4.0                0                                                 2565
                   1                                                  297
5.0                0                                                  678
                   1                                                   68
6.0                0                                                  134
                   1                                                   24
7.0                0                                                   46
                   1                                                    5
8.0                0                                                   22
                   1                                                    2
9.0                0                                                    5
10.0               0                                                    5
13.0               0                                                    1
20.0               0                                                    1

                                     DebtRatio  MonthlyIncome  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                     81807          81807
                   1                      5095           5095
1.0                0                     28126          28126
                   1                      2114           2114
2.0                0                     17938          17938
                   1                      1584           1584
3.0                0                      8646           8646
                   1                       837            837
4.0                0                      2565           2565
                   1                       297            297
5.0                0                       678            678
                   1                        68             68
6.0                0                       134            134
                   1                        24             24
7.0                0                        46             46
                   1                         5              5
8.0                0                        22             22
                   1                         2              2
9.0                0                         5              5
10.0               0                         5              5
13.0               0                         1              1
20.0               0                         1              1

                                     NumberOfOpenCreditLinesAndLoans  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                                           81807
                   1                                            5095
1.0                0                                           28126
                   1                                            2114
2.0                0                                           17938
                   1                                            1584
3.0                0                                            8646
                   1                                             837
4.0                0                                            2565
                   1                                             297
5.0                0                                             678
                   1                                              68
6.0                0                                             134
                   1                                              24
7.0                0                                              46
                   1                                               5
8.0                0                                              22
                   1                                               2
9.0                0                                               5
10.0               0                                               5
13.0               0                                               1
20.0               0                                               1

                                     NumberOfTimes90DaysLate  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                                   81807
                   1                                    5095
1.0                0                                   28126
                   1                                    2114
2.0                0                                   17938
                   1                                    1584
3.0                0                                    8646
                   1                                     837
4.0                0                                    2565
                   1                                     297
5.0                0                                     678
                   1                                      68
6.0                0                                     134
                   1                                      24
7.0                0                                      46
                   1                                       5
8.0                0                                      22
                   1                                       2
9.0                0                                       5
10.0               0                                       5
13.0               0                                       1
20.0               0                                       1

                                     NumberRealEstateLoansOrLines  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                                        81807
                   1                                         5095
1.0                0                                        28126
                   1                                         2114
2.0                0                                        17938
                   1                                         1584
3.0                0                                         8646
                   1                                          837
4.0                0                                         2565
                   1                                          297
5.0                0                                          678
                   1                                           68
6.0                0                                          134
                   1                                           24
7.0                0                                           46
                   1                                            5
8.0                0                                           22
                   1                                            2
9.0                0                                            5
10.0               0                                            5
13.0               0                                            1
20.0               0                                            1

                                     NumberOfTime60-89DaysPastDueNotWorse  \
NumberOfDependents SeriousDlqin2yrs
0.0                0                                                81807
                   1                                                 5095
1.0                0                                                28126
                   1                                                 2114
2.0                0                                                17938
                   1                                                 1584
3.0                0                                                 8646
                   1                                                  837
4.0                0                                                 2565
                   1                                                  297
5.0                0                                                  678
                   1                                                   68
6.0                0                                                  134
                   1                                                   24
7.0                0                                                   46
                   1                                                    5
8.0                0                                                   22
                   1                                                    2
9.0                0                                                    5
10.0               0                                                    5
13.0               0                                                    1
20.0               0                                                    1

                                     index
NumberOfDependents SeriousDlqin2yrs
0.0                0                 81807
                   1                  5095
1.0                0                 28126
                   1                  2114
2.0                0                 17938
                   1                  1584
3.0                0                  8646
                   1                   837
4.0                0                  2565
                   1                   297
5.0                0                   678
                   1                    68
6.0                0                   134
                   1                    24
7.0                0                    46
                   1                     5
8.0                0                    22
                   1                     2
9.0                0                     5
10.0               0                     5
13.0               0                     1
20.0               0                     1

In [57]:
#groupByDependents['age'][0]/groupByDependents['age'][0].sum()
groupByDependents['index'][:,1]
numberofdependents_dlq=groupByDependents['index'][:,1]/(groupByDependents['index'][:,0] + groupByDependents['index'][:,1])

In [58]:
pd.DataFrame(numberofdependents_dlq)

                       index
NumberOfDependents
0.0                 0.058629
1.0                 0.069907
2.0                 0.081139
3.0                 0.088263
4.0                 0.103774
5.0                 0.091153
6.0                 0.151899
7.0                 0.098039
8.0                 0.083333
9.0                      NaN
10.0                     NaN
13.0                     NaN
20.0                     NaN

In [59]:
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import plotly
plotly.__version__
import plotly
from plotly.graph_objs import Scatter, Layout
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
# Scientific libraries
from numpy import arange,array,ones
from scipy import stats
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True) 

numberofdependents_dlq=numberofdependents_dlq.dropna()

Xrange=np.arange(0,groupByDependents['age'][:,1].count())

Y=numberofdependents_dlq.as_matrix()
X=Xrange

print Y

slope, intercept, r_value, p_value, std_err = stats.linregress(X,Y)
line = slope*X+intercept

trace1 = go.Scatter(
                  x=X, 
                  y=Y, 
                  mode='line',
                  marker=go.Marker(color='rgb((255, 127, 14)'),
                  name='Data'
                  )

trace2 = go.Scatter(
                  x=X, 
                  y=line, 
                  mode='lines',
                  marker=go.Marker(color='rgb(31, 119, 180)'),
                  name='fit'
                  )


annotation = go.Annotation(
                  x=4,
                  y=0.14,
                  text='$R^2 = 0.9551,\\Y = 0.716X + 19.18$',
                  showarrow=False,
                  font=go.Font(size=16)
                  )

layout = go.Layout(
                title='Number of dependents to delinquency',
                plot_bgcolor='rgb(229, 229, 229)',
                  xaxis=go.XAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  yaxis=go.YAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  annotations=[annotation]
                )

data = [trace1, trace2]

#print x

#data = [trace]

# Plot and embed in ipython notebook!

fig = go.Figure(data=data, layout=layout)
#fig = go.Figure(data=data)

plotly.offline.iplot(fig, filename='Number of dependents to delinquency')
print "We can see that as number of dependents are growing delinquency rate is increasing"
print "R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination, "

[ 0.05862926  0.06990741  0.08113923  0.08826321  0.10377358  0.09115282
  0.15189873  0.09803922  0.08333333]

We can see that as number of dependents are growing delinquency rate is increasing
R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination,

In [7]:
test.loc[ (test['age']>=100),'age']='100s'
test.loc[ (test['age']<30) & (test['age']>=20),'age']='20s'
test.loc[ (test['age']<40) & (test['age']>=30),'age']='30s'
test.loc[ (test['age']<50) & (test['age']>=40),'age']='40s'
test.loc[ (test['age']<60) & (test['age']>=50),'age']='50s'
test.loc[ (test['age']<70) & (test['age']>=60),'age']='60s'
test.loc[ (test['age']<80) & (test['age']>=70),'age']='70s'
test.loc[ (test['age']<90) & (test['age']>=80),'age']='80s'
test.loc[ (test['age']<100) & (test['age']>=90),'age']='90s'
test.loc[ (test['age']<20) & (test['age']>=0),'age']='10s'

In [8]:
groupByAge=test.groupby(['age', 'dlq']).count()
groupByAge['index'][:,1]
age_dlq=groupByAge['index'][:,1]/(groupByAge['index'][:,0] + groupByAge['index'][:,1])

In [32]:
a=pd.DataFrame(age_dlq)
#a.icol(0)
#print a['index']
pd.age_dlq

age
100s         NaN
20s     0.030267
30s     0.029379
40s     0.024250
50s     0.017285
60s     0.005881
70s     0.002791
80s     0.000833
90s     0.004301
Name: index, dtype: float64

In [199]:

test=pd.read_csv('pred_xgb_record.csv')
test.head()

test=pd.read_csv('pred_xgb_record.csv')
test.head()
test['dlq']=pd.DataFrame(np.ones(test.size))
test.loc[(test['prob']<=0.5), 'dlq'] = int(0)
test[test['dlq']==1]


test.loc[ (test['age']>=100),'age']='100s'
test.loc[ (test['age']<25) & (test['age']>=20),'age']='20s'
test.loc[ (test['age']<30) & (test['age']>=25),'age']='25s'

test.loc[ (test['age']<35) & (test['age']>=30),'age']='30s'
test.loc[ (test['age']<40) & (test['age']>=35),'age']='35s'

test.loc[ (test['age']<45) & (test['age']>=40),'age']='40s'
test.loc[ (test['age']<50) & (test['age']>=45),'age']='45s'

test.loc[ (test['age']<55) & (test['age']>=50),'age']='50s'
test.loc[ (test['age']<60) & (test['age']>=55),'age']='55s'

test.loc[ (test['age']<65) & (test['age']>=60),'age']='60s'
test.loc[ (test['age']<70) & (test['age']>=65),'age']='65s'

test.loc[ (test['age']<75) & (test['age']>=70),'age']='70s'
test.loc[ (test['age']<80) & (test['age']>=75),'age']='75s'

test.loc[ (test['age']<85) & (test['age']>=80),'age']='80s'
test.loc[ (test['age']<90) & (test['age']>=85),'age']='85s'

test.loc[ (test['age']<95) & (test['age']>=90),'age']="90s"
test.loc[ (test['age']<100) & (test['age']>=95),'age']="95s"

test.loc[ (test['age']<20) & (test['age']>=0),'age']='10s'



groupByAgeWorse=test.groupby(['age'])
a=groupByAgeWorse.mean()
a.to_csv('allagewise.csv')
a
#test[test['NumberOfDependents']>2]

,index,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,prob,dlq
age,,,,,,,,,,,,,
100s,22049.500000,NaN,0.185244,0.500000,436.500906,5059.068671,5.250000,0.000000,0.500000,0.250000,0.250000,0.076571,0.000000
20s,49535.319742,NaN,0.583496,5.722461,40.230484,1836.603260,2.266094,5.696710,0.012876,5.648784,0.180973,0.117131,0.020744
25s,50793.772474,NaN,4.218682,1.181352,88.919779,3398.747939,5.044836,1.096364,0.201874,1.015838,0.353558,0.123311,0.033237
30s,51339.204073,NaN,7.656208,0.449891,170.520052,4813.801207,6.802473,0.339491,0.688000,0.274473,0.706618,0.109348,0.030109
35s,50241.861937,NaN,9.456563,0.514282,252.195502,5936.462024,7.588830,0.352183,0.993730,0.299814,1.150139,0.101443,0.028797
40s,50507.100475,NaN,5.924415,0.428931,296.592005,6822.448125,8.209153,0.241029,1.171125,0.200485,1.355858,0.093639,0.027775
45s,50806.039300,NaN,8.839475,0.391965,363.562293,7474.880824,8.832697,0.178520,1.245346,0.156404,1.320286,0.085586,0.021241
50s,51085.227742,NaN,4.879818,0.392097,438.397034,7379.457318,9.387903,0.192500,1.239355,0.164355,1.008871,0.078582,0.019435
55s,50444.366452,NaN,1.221211,0.409953,482.567232,7529.167911,9.684705,0.220028,1.251262,0.204977,0.677310,0.066316,0.014964
60s,50936.253224,NaN,5.904680,0.261049,462.443846,7688.541166,9.596303,0.102064,1.190800,0.096045,0.453224,0.049487,0.007739
65s,50980.003407,NaN,3.940799,0.193793,412.638208,8288.843997,9.179031,0.069140,1.024224,0.064598,0.298385,0.037755,0.003154
70s,50276.291326,NaN,2.451988,0.132024,345.773717,6798.101241,8.821058,0.032006,0.864157,0.033824,0.239680,0.034731,0.003273
75s,50755.232381,NaN,2.402584,0.121561,266.736361,8121.435432,8.166623,0.030390,0.616715,0.025675,0.225046,0.031618,0.002096
80s,51616.617181,NaN,4.814022,0.091743,228.142347,6100.165588,7.592994,0.025438,0.464971,0.022102,0.195997,0.028778,0.000834
85s,50669.935993,NaN,1.500533,0.092269,139.629634,5801.296106,6.657523,0.018288,0.300914,0.020781,0.191189,0.026654,0.000831
90s,50223.247549,NaN,0.097385,0.095588,131.439960,6089.322780,6.772059,0.031863,0.227941,0.031863,0.252451,0.028292,0.004902
95s,54814.789474,NaN,0.087024,0.070175,1623.030165,6269.426541,4.982456,0.000000,0.087719,0.035088,0.192982,0.022747,0.000000

In [203]:

test=pd.read_csv('pred_xgb_record.csv')
test.head()

test=pd.read_csv('pred_xgb_record.csv')
test.head()
test['dlq']=pd.DataFrame(np.ones(test.size))
test.loc[(test['prob']<=0.5), 'dlq'] = int(0)
test[test['dlq']==1]


test.loc[test['MonthlyIncome']<0,'MonthlyIncome']=0
test.loc[test['MonthlyIncome']>=15000,'MonthlyIncome']=20
test.loc[((test['MonthlyIncome']>=0)&(test['MonthlyIncome']<2500)), 'MonthlyIncome']=2
test.loc[((test['MonthlyIncome']>=2500) & (test['MonthlyIncome']<5000)), 'MonthlyIncome'] =5
test.loc[((test['MonthlyIncome']>=5000) & (test['MonthlyIncome']<7500)), 'MonthlyIncome'] =7
test.loc[((test['MonthlyIncome']>=7500) & (test['MonthlyIncome']<10000)), 'MonthlyIncome'] =10
test.loc[((test['MonthlyIncome']>=10000) & (test['MonthlyIncome']<12500)), 'MonthlyIncome'] =12
test.loc[((test['MonthlyIncome']>=12500) & (test['MonthlyIncome']<15000)), 'MonthlyIncome'] =15



groupByIncomeAll=test.groupby(['MonthlyIncome'])
a=groupByIncomeAll.mean()
a.to_csv('allincomewise.csv')
a
#test[test['NumberOfDependents']>2]

,index,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,prob,dlq
MonthlyIncome,,,,,,,,,,,,,
2.0,50629.636576,NaN,9.399880,49.534027,1.350347,253.183764,7.565052,1.219576,0.889979,1.184614,0.708967,0.086083,0.021150
5.0,50872.526919,NaN,5.859037,49.049945,0.416636,157.609640,7.544877,0.264231,0.722108,0.219133,0.679838,0.097481,0.029416
7.0,50805.072628,NaN,3.170700,53.566020,0.261205,469.525661,8.284351,0.101264,0.938131,0.075182,0.672583,0.067463,0.014526
10.0,50571.715374,NaN,4.773217,56.517123,0.214274,568.308363,9.536700,0.050381,1.328801,0.040677,0.923667,0.050273,0.007221
12.0,50722.985792,NaN,6.009841,55.111539,0.249502,245.635958,10.713185,0.064268,1.569911,0.069977,1.152171,0.049680,0.005975
15.0,50864.251017,NaN,3.463801,54.177449,0.227726,91.773490,11.093161,0.034011,1.872828,0.041774,1.261368,0.050523,0.004067

In [51]:

test=pd.read_csv('pred_xgb_record.csv')
test.head()

test=pd.read_csv('pred_xgb_record.csv')
test.head()
test['dlq']=pd.DataFrame(np.ones(test.size))
test.loc[(test['prob']<=0.5), 'dlq'] = int(0)
test[test['dlq']==1]


test.loc[ (test['age']>=100),'age']='100s'
test.loc[ (test['age']<30) & (test['age']>=20),'age']='20s'
test.loc[ (test['age']<40) & (test['age']>=30),'age']='30s'
test.loc[ (test['age']<50) & (test['age']>=40),'age']='40s'
test.loc[ (test['age']<60) & (test['age']>=50),'age']='50s'
test.loc[ (test['age']<70) & (test['age']>=60),'age']='60s'
test.loc[ (test['age']<80) & (test['age']>=70),'age']='70s'
test.loc[ (test['age']<90) & (test['age']>=80),'age']='80s'
test.loc[ (test['age']<100) & (test['age']>=90),'age']="90s"
test.loc[ (test['age']<20) & (test['age']>=0),'age']='10s'


groupByAge=test.groupby(['age', 'dlq']).count()
groupByAge['index'][:,1]
age_dlq=groupByAge['index'][:,1]/(groupByAge['index'][:,0] + groupByAge['index'][:,1])



a=pd.DataFrame(age_dlq)
#a.icol(0)
a['index']


age_dlq=age_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByAge['index'][:,1].count())

Y=age_dlq.as_matrix()[0:]
X=Xrange
print X
print Y
#a.unstack(level=-1

import re

_nsre = re.compile('([0-9]+)')
def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower()
            for text in re.split(_nsre, s)]  
keys=age_dlq.keys()
keys=list(keys)
keys.sort(key=natural_sort_key)
print keys
print Y





d = {'age': keys, 'per': Y}
dfoutput=pd.DataFrame(d,index=None)
dfoutput.to_csv('age_per.csv')
dfoutput

[0 1 2 3 4 5 6 7]
[ 0.03026696  0.02937948  0.02424997  0.01728467  0.00588055  0.0027909
  0.0008331   0.00430108]
['20s', '30s', '40s', '50s', '60s', '70s', '80s', '90s']
[ 0.03026696  0.02937948  0.02424997  0.01728467  0.00588055  0.0027909
  0.0008331   0.00430108]

   age       per
0  20s  0.030267
1  30s  0.029379
2  40s  0.024250
3  50s  0.017285
4  60s  0.005881
5  70s  0.002791
6  80s  0.000833
7  90s  0.004301

In [10]:
Xrange=np.arange(0,groupByAge['index'][:,1].count()-1)+2
print Xrange

[2 3 4 5 6 7 8]

In [44]:

age_dlq=age_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByAge['index'][:,1].count())

Y=age_dlq.as_matrix()[0:]
X=Xrange
print X
print Y
#a.unstack(level=-1

[0 1 2 3 4 5 6 7]
[ 0.03026696  0.02937948  0.02424997  0.01728467  0.00588055  0.0027909
  0.0008331   0.00430108]

In [45]:
import re

_nsre = re.compile('([0-9]+)')
def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower()
            for text in re.split(_nsre, s)]  
keys=age_dlq.keys()
keys=list(keys)
keys.sort(key=natural_sort_key)
print keys
print Y

['20s', '30s', '40s', '50s', '60s', '70s', '80s', '90s']
[ 0.03026696  0.02937948  0.02424997  0.01728467  0.00588055  0.0027909
  0.0008331   0.00430108]

In [46]:
d = {'age': keys, 'per': Y}
dfoutput=pd.DataFrame(d,index=None)
dfoutput.to_csv('age_per.csv')

In [47]:
dfoutput

   age       per
0  20s  0.030267
1  30s  0.029379
2  40s  0.024250
3  50s  0.017285
4  60s  0.005881
5  70s  0.002791
6  80s  0.000833
7  90s  0.004301

In [114]:
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import plotly
plotly.__version__
import plotly
from plotly.graph_objs import Scatter, Layout
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
# Scientific libraries
from numpy import arange,array,ones
from scipy import stats
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True) 

age_dlq=age_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByAge['index'][:,1].count()-1)

Y=age_dlq.as_matrix()[1:]
X=Xrange

print Y

slope, intercept, r_value, p_value, std_err = stats.linregress(X,Y)
line = slope*X+intercept

trace1 = go.Scatter(
                  x=X, 
                  y=Y, 
                  mode='line',
                  marker=go.Marker(color='rgb((255, 127, 14)'),
                  name='Data'
                  )

trace2 = go.Scatter(
                  x=X, 
                  y=line, 
                  mode='lines',
                  marker=go.Marker(color='rgb(31, 119, 180)'),
                  name='fit'
                  )


annotation = go.Annotation(
                  x=4,
                  y=0.14,
                  text=r_value,
                  showarrow=False,
                  font=go.Font(size=16)
                  )

layout = go.Layout(
                title='Age to delinquency',
                plot_bgcolor='rgb(229, 229, 229)',
                  xaxis=go.XAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  yaxis=go.YAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  annotations=[annotation]
                )

data = [trace1, trace2]

#print x

#data = [trace]

# Plot and embed in ipython notebook!

fig = go.Figure(data=data, layout=layout)
#fig = go.Figure(data=data)

plotly.offline.iplot(fig, filename='Age to delinquency')
print "We can see that as age is increasing delinquency is reducing as they become more mature or have enough income"
print "R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination, "

[ 0.11734694  0.10072036  0.08371877  0.06452892  0.0363259   0.02433645
  0.0204878   0.01928783]

We can see that as age is increasing delinquency is reducing as they become more mature or have enough income
R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination,

In [52]:

test=pd.read_csv('pred_xgb_record.csv')
test.head()

test=pd.read_csv('pred_xgb_record.csv')
test.head()
test['dlq']=pd.DataFrame(np.ones(test.size))
test.loc[(test['prob']<=0.5), 'dlq'] = int(0)
test[test['dlq']==1]

,index,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents,prob,dlq
23,24,NaN,0.957442,69,2,0.666338,3041.000000,8,1,1,1,1.0,0.517759,1.0
69,70,NaN,1.000000,52,98,0.020303,2708.000000,0,98,0,98,0.0,0.647222,1.0
123,124,NaN,2.182724,49,0,497.000000,5714.088497,2,2,0,1,0.0,0.552055,1.0
166,167,NaN,49.923077,62,1,1396.000000,5713.382214,6,2,0,1,0.0,0.625771,1.0
280,281,NaN,1.066445,35,1,0.165934,2500.000000,2,3,0,0,4.0,0.620639,1.0
356,357,NaN,0.978913,28,2,675.000000,3560.019305,7,1,0,2,0.0,0.658776,1.0
404,405,NaN,1.103039,58,2,0.328350,7625.000000,13,5,1,7,1.0,0.777454,1.0
405,406,NaN,1.000000,52,0,0.436839,14375.000000,4,3,1,2,2.0,0.656278,1.0
625,626,NaN,0.759448,42,3,0.905240,4083.000000,17,1,1,0,2.0,0.569140,1.0
643,644,NaN,0.955719,55,2,0.591664,2950.000000,6,1,1,1,2.0,0.578963,1.0
653,654,NaN,1.076412,27,1,76.000000,4147.309079,4,1,0,0,1.0,0.552180,1.0
729,730,NaN,1.176823,39,1,0.590147,1907.000000,5,1,0,0,6.0,0.543116,1.0
844,845,NaN,1.130032,67,2,980.000000,5868.603066,7,1,0,3,0.0,0.658972,1.0
845,846,NaN,1.006821,36,8,0.698026,3900.000000,15,0,1,1,2.0,0.668848,1.0
893,894,NaN,0.959008,31,3,0.386005,3043.000000,5,2,0,2,1.0,0.713710,1.0
979,980,NaN,0.783350,43,5,0.287578,8967.000000,9,2,2,0,0.0,0.539289,1.0
1157,1158,NaN,1.000000,37,0,0.554189,1300.000000,4,1,0,2,3.0,0.572918,1.0
1176,1177,NaN,1.000000,25,98,0.000000,2935.000000,0,98,0,98,0.0,0.540700,1.0
1187,1188,NaN,0.974169,33,1,0.785844,550.000000,3,3,0,1,0.0,0.639562,1.0
1192,1193,NaN,1.045105,30,1,0.685997,4741.000000,12,1,0,0,2.0,0.558759,1.0
1206,1207,NaN,0.995798,41,1,0.329950,6600.000000,9,3,1,0,2.0,0.506796,1.0
1214,1215,NaN,1.000000,64,1,0.889688,2501.000000,3,8,1,1,0.0,0.691883,1.0
1233,1234,NaN,1.475083,44,2,0.615195,8120.000000,10,9,1,0,3.0,0.750486,1.0
1234,1235,NaN,0.976398,39,3,0.858886,7950.000000,9,6,2,3,2.0,0.831659,1.0
1275,1276,NaN,1.000000,58,0,1461.000000,9127.616635,6,2,0,2,3.0,0.534485,1.0
1293,1294,NaN,1.000000,59,2,0.493005,1500.000000,3,6,0,0,0.0,0.610474,1.0
1368,1369,NaN,0.911537,49,3,4.235620,3250.000000,26,0,0,1,0.0,0.566647,1.0
1418,1419,NaN,8.601990,58,1,0.230402,4400.000000,10,2,0,0,0.0,0.516352,1.0
1554,1555,NaN,1.000000,48,1,0.309463,4300.000000,2,2,0,1,0.0,0.553851,1.0
1557,1558,NaN,1.000000,46,1,0.139812,4033.000000,8,3,0,0,0.0,0.512662,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99337,99338,NaN,1.000000,53,1,0.405313,3500.000000,3,3,1,0,3.0,0.514214,1.0
99399,99400,NaN,1.659280,41,2,0.109918,5494.000000,4,3,0,0,1.0,0.590966,1.0
99418,99419,NaN,1.000000,31,1,0.281489,5104.000000,8,4,0,0,1.0,0.553392,1.0
99439,99440,NaN,1.000000,43,2,0.790631,3500.000000,7,3,2,0,2.0,0.641904,1.0
99533,99534,NaN,0.877714,43,3,0.642220,5153.000000,10,1,1,0,0.0,0.509406,1.0
99663,99664,NaN,1.000000,48,4,1.585334,1540.000000,5,3,3,1,0.0,0.748740,1.0
99740,99741,NaN,1.000364,31,6,0.805344,1833.000000,5,0,2,1,0.0,0.536187,1.0
99906,99907,NaN,0.787213,25,2,0.184064,3400.000000,4,2,0,2,0.0,0.633554,1.0
99924,99925,NaN,0.956806,52,1,0.584233,8891.000000,4,1,2,2,0.0,0.616157,1.0
100061,100062,NaN,1.000000,31,98,0.000000,2570.000000,0,98,0,98,1.0,0.562607,1.0
100078,100079,NaN,1.381032,36,1,0.202024,2370.000000,3,2,0,0,3.0,0.584089,1.0
100147,100148,NaN,0.690810,52,4,3.181818,1000.000000,11,7,1,1,1.0,0.689604,1.0
100163,100164,NaN,0.337625,47,5,1.239329,2740.000000,11,1,2,1,0.0,0.503586,1.0
100202,100203,NaN,1.000000,33,1,40.000000,4371.405892,1,1,0,1,1.0,0.553378,1.0
100242,100243,NaN,0.942359,44,2,0.780844,5000.000000,15,2,2,4,3.0,0.767986,1.0
100282,100283,NaN,1.000000,32,2,0.471176,3000.000000,7,1,1,3,1.0,0.642383,1.0
100317,100318,NaN,0.946789,50,3,0.498500,7000.000000,6,2,1,1,2.0,0.624652,1.0
100357,100358,NaN,0.635915,42,0,0.159447,6070.000000,4,5,0,2,3.0,0.605384,1.0
100418,100419,NaN,1.057295,37,2,1.346827,2000.000000,7,0,1,1,0.0,0.513072,1.0
100483,100484,NaN,0.774461,41,2,0.918214,5061.000000,11,1,3,0,1.0,0.523821,1.0
100532,100533,NaN,1.013598,50,2,0.433930,5198.000000,6,1,1,0,0.0,0.538742,1.0
100560,100561,NaN,0.962025,31,0,1.071853,1850.000000,5,1,1,1,1.0,0.507860,1.0
100569,100570,NaN,1.684631,54,0,0.165727,3191.000000,2,2,0,1,1.0,0.535142,1.0
100869,100870,NaN,1.004933,44,1,0.390652,4000.000000,6,2,0,0,4.0,0.529771,1.0
100892,100893,NaN,1.000000,39,0,0.130478,6000.000000,2,5,0,1,1.0,0.592904,1.0
101033,101034,NaN,0.676524,48,3,0.490448,5600.000000,7,3,3,2,0.0,0.679862,1.0
101207,101208,NaN,1.000000,42,98,12.000000,-5495.995601,0,98,0,98,0.0,0.707371,1.0
101283,101284,NaN,1.117520,51,5,0.807154,4500.000000,9,2,2,1,1.0,0.766672,1.0
101423,101424,NaN,0.798160,38,0,0.526438,5162.000000,8,3,2,1,2.0,0.545310,1.0
101482,101483,NaN,1.000000,33,98,0.000000,2000.000000,0,98,0,98,3.0,0.550186,1.0

In [53]:
test.loc[test['MonthlyIncome']<0,'MonthlyIncome']=0
test.loc[test['MonthlyIncome']>=15000,'MonthlyIncome']='20K'
test.loc[((test['MonthlyIncome']>=0)&(test['MonthlyIncome']<2500)), 'MonthlyIncome']='2K'
test.loc[((test['MonthlyIncome']>=2500) & (test['MonthlyIncome']<5000)), 'MonthlyIncome'] ='5K'
test.loc[((test['MonthlyIncome']>=5000) & (test['MonthlyIncome']<7500)), 'MonthlyIncome'] ='7K'
test.loc[((test['MonthlyIncome']>=7500) & (test['MonthlyIncome']<10000)), 'MonthlyIncome'] ='10K'
test.loc[((test['MonthlyIncome']>=10000) & (test['MonthlyIncome']<12500)), 'MonthlyIncome'] ='12K'
test.loc[((test['MonthlyIncome']>=12500) & (test['MonthlyIncome']<15000)), 'MonthlyIncome'] ='15K'

In [61]:
groupByMonthlyIncome=test.groupby(['MonthlyIncome','dlq']).count()
#groupByDependents['age'][0]/groupByDependents['age'][0].sum()
groupByMonthlyIncome['index'][:,1]
income_dlq=groupByMonthlyIncome['index'][:,1]/(groupByMonthlyIncome['index'][:,0] + groupByMonthlyIncome['index'][:,1])


a=pd.DataFrame(income_dlq)
#a.icol(0)



income_dlq=income_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByMonthlyIncome['index'][:,1].count())

Y=income_dlq.as_matrix()[0:]
X=Xrange
print X
print Y
#a.unstack(level=-1




import re

_nsre = re.compile('([0-9]+)')
def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower()
            for text in re.split(_nsre, s)]  
keys=income_dlq.keys()
keys=list(keys)
keys.sort(key=natural_sort_key)
print keys

d = {'income': keys, 'per': Y}
dfoutput=pd.DataFrame(d,index=None)
dfoutput.to_csv('income_per.csv')
dfoutput
#income_dlq=income_dlq[keys]
#for key in keys:
#    print income_dlq[key]

[0 1 2 3 4 5 6]
[ 0.00722144  0.0059753   0.00406654  0.00416992  0.02699309  0.02941609
  0.0145256 ]
['2K', '5K', '7K', '10K', '12K', '15K', '20K']

  income       per
0     2K  0.007221
1     5K  0.005975
2     7K  0.004067
3    10K  0.004170
4    12K  0.026993
5    15K  0.029416
6    20K  0.014526

In [126]:
groupByMonthlyIncome=train_discretized.groupby(['MonthlyIncome','SeriousDlqin2yrs']).count()

In [127]:
groupByMonthlyIncome

                                RevolvingUtilizationOfUnsecuredLines    age  \
MonthlyIncome SeriousDlqin2yrs
10K           0                                                23873  23873
              1                                                 1151   1151
12K           0                                                10681  10681
              1                                                  447    447
15K           0                                                 4101   4101
              1                                                  195    195
20K           0                                                 5504   5504
              1                                                  268    268
2K            0                                                15543  15543
              1                                                 1576   1576
5K            0                                                36101  36101
              1                                                 3713   3713
7K            0                                                44171  44171
              1                                                 2676   2676

                                NumberOfTime30-59DaysPastDueNotWorse  \
MonthlyIncome SeriousDlqin2yrs
10K           0                                                23873
              1                                                 1151
12K           0                                                10681
              1                                                  447
15K           0                                                 4101
              1                                                  195
20K           0                                                 5504
              1                                                  268
2K            0                                                15543
              1                                                 1576
5K            0                                                36101
              1                                                 3713
7K            0                                                44171
              1                                                 2676

                                DebtRatio  NumberOfOpenCreditLinesAndLoans  \
MonthlyIncome SeriousDlqin2yrs
10K           0                     23873                            23873
              1                      1151                             1151
12K           0                     10681                            10681
              1                       447                              447
15K           0                      4101                             4101
              1                       195                              195
20K           0                      5504                             5504
              1                       268                              268
2K            0                     15543                            15543
              1                      1576                             1576
5K            0                     36101                            36101
              1                      3713                             3713
7K            0                     44171                            44171
              1                      2676                             2676

                                NumberOfTimes90DaysLate  \
MonthlyIncome SeriousDlqin2yrs
10K           0                                   23873
              1                                    1151
12K           0                                   10681
              1                                     447
15K           0                                    4101
              1                                     195
20K           0                                    5504
              1                                     268
2K            0                                   15543
              1                                    1576
5K            0                                   36101
              1                                    3713
7K            0                                   44171
              1                                    2676

                                NumberRealEstateLoansOrLines  \
MonthlyIncome SeriousDlqin2yrs
10K           0                                        23873
              1                                         1151
12K           0                                        10681
              1                                          447
15K           0                                         4101
              1                                          195
20K           0                                         5504
              1                                          268
2K            0                                        15543
              1                                         1576
5K            0                                        36101
              1                                         3713
7K            0                                        44171
              1                                         2676

                                NumberOfTime60-89DaysPastDueNotWorse  \
MonthlyIncome SeriousDlqin2yrs
10K           0                                                23873
              1                                                 1151
12K           0                                                10681
              1                                                  447
15K           0                                                 4101
              1                                                  195
20K           0                                                 5504
              1                                                  268
2K            0                                                15543
              1                                                 1576
5K            0                                                36101
              1                                                 3713
7K            0                                                44171
              1                                                 2676

                                NumberOfDependents  index
MonthlyIncome SeriousDlqin2yrs
10K           0                              23873  23873
              1                               1151   1151
12K           0                              10681  10681
              1                                447    447
15K           0                               4101   4101
              1                                195    195
20K           0                               5504   5504
              1                                268    268
2K            0                              15543  15543
              1                               1576   1576
5K            0                              36101  36101
              1                               3713   3713
7K            0                              44171  44171
              1                               2676   2676

In [128]:
#groupByDependents['age'][0]/groupByDependents['age'][0].sum()
groupByMonthlyIncome['index'][:,1]
income_dlq=groupByMonthlyIncome['index'][:,1]/(groupByMonthlyIncome['index'][:,0] + groupByMonthlyIncome['index'][:,1])

In [152]:
import re

_nsre = re.compile('([0-9]+)')
def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower()
            for text in re.split(_nsre, s)]  
keys=income_dlq.keys()
keys=list(keys)
keys.sort(key=natural_sort_key)
print keys

income_dlq=income_dlq[keys]
#for key in keys:
#    print income_dlq[key]

['2K', '5K', '7K', '10K', '12K', '15K', '20K']

In [161]:
print X

[0 1 2 3 4 5]

In [166]:
#groupByDependents['age'][0]/groupByDependents['age'][0].sum()
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import plotly
plotly.__version__
import plotly
from plotly.graph_objs import Scatter, Layout
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
# Scientific libraries
from numpy import arange,array,ones
from scipy import stats
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True) 

income_dlq=income_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByMonthlyIncome['index'][:,1].count())

Y=income_dlq.as_matrix()
X=Xrange

print keys
print Y

slope, intercept, r_value, p_value, std_err = stats.linregress(X,Y)
line = slope*X+intercept

trace1 = go.Scatter(
                  x=X, 
                  y=Y, 
                  mode='line',
                  marker=go.Marker(color='rgb((255, 127, 14)'),
                  name='Data'
                  )

trace2 = go.Scatter(
                  x=X, 
                  y=line, 
                  mode='lines',
                  marker=go.Marker(color='rgb(31, 119, 180)'),
                  name='fit'
                  )


annotation = go.Annotation(
                  x=4,
                  y=0.14,
                  text=r_value,
                  showarrow=False,
                  font=go.Font(size=16)
                  )

layout = go.Layout(
                title='Income to delinquency',
                plot_bgcolor='rgb(229, 229, 229)',
                  xaxis=go.XAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  yaxis=go.YAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  annotations=[annotation]
                )

data = [trace1, trace2]

#print x

#data = [trace]

# Plot and embed in ipython notebook!

fig = go.Figure(data=data, layout=layout)
#fig = go.Figure(data=data)


plotly.offline.iplot(fig, filename='Income to delinquency')
print "We can see that as income is increasing delinquency is decreasing thats very intuitive"
print "R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination"

['2K', '5K', '7K', '10K', '12K', '15K', '20K']
[ 0.09206145  0.09325865  0.05712212  0.04599584  0.04016894  0.04539106
  0.04643105]

We can see that as income is increasing delinquency is decreasing thats very intuitive
R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination

In [82]:
bins = np.linspace(test.RevolvingUtilizationOfUnsecuredLines.min(), test.RevolvingUtilizationOfUnsecuredLines.max(),50 )
groupByutilization = test.groupby([pd.cut(test.RevolvingUtilizationOfUnsecuredLines, bins),'dlq']).count()

#groupByDependents=train_discretized.groupby(['NumberOfDependents', 'SeriousDlqin2yrs']).count()

In [83]:
groupByutilization

                                            index  SeriousDlqin2yrs  \
RevolvingUtilizationOfUnsecuredLines dlq
(0, 445.327]                         0.0  92321.0               0.0
                                     1.0   1746.0               0.0
(445.327, 890.653]                   0.0     15.0               0.0
                                     1.0      NaN               NaN
(890.653, 1335.98]                   0.0     19.0               0.0
                                     1.0      NaN               NaN
(1335.98, 1781.306]                  0.0     12.0               0.0
                                     1.0      NaN               NaN
(1781.306, 2226.633]                 0.0     12.0               0.0
                                     1.0      NaN               NaN
(2226.633, 2671.959]                 0.0      4.0               0.0
                                     1.0      NaN               NaN
(2671.959, 3117.286]                 0.0      8.0               0.0
                                     1.0      NaN               NaN
(3117.286, 3562.612]                 0.0      9.0               0.0
                                     1.0      NaN               NaN
(3562.612, 4007.939]                 0.0      6.0               0.0
                                     1.0      NaN               NaN
(4007.939, 4453.265]                 0.0      3.0               0.0
                                     1.0      1.0               0.0
(4453.265, 4898.592]                 0.0      4.0               0.0
                                     1.0      NaN               NaN
(4898.592, 5343.918]                 0.0      2.0               0.0
                                     1.0      NaN               NaN
(5343.918, 5789.245]                 0.0      1.0               0.0
                                     1.0      NaN               NaN
(5789.245, 6234.571]                 0.0      1.0               0.0
                                     1.0      NaN               NaN
(6234.571, 6679.898]                 0.0      3.0               0.0
                                     1.0      NaN               NaN
...                                           ...               ...
(15141.102, 15586.429]               0.0      NaN               NaN
                                     1.0      NaN               NaN
(15586.429, 16031.755]               0.0      1.0               0.0
                                     1.0      NaN               NaN
(16031.755, 16477.0816]              0.0      2.0               0.0
                                     1.0      NaN               NaN
(16477.0816, 16922.408]              0.0      NaN               NaN
                                     1.0      NaN               NaN
(16922.408, 17367.735]               0.0      NaN               NaN
                                     1.0      NaN               NaN
(17367.735, 17813.0612]              0.0      NaN               NaN
                                     1.0      NaN               NaN
(17813.0612, 18258.388]              0.0      NaN               NaN
                                     1.0      NaN               NaN
(18258.388, 18703.714]               0.0      NaN               NaN
                                     1.0      NaN               NaN
(18703.714, 19149.0408]              0.0      NaN               NaN
                                     1.0      NaN               NaN
(19149.0408, 19594.367]              0.0      NaN               NaN
                                     1.0      NaN               NaN
(19594.367, 20039.694]               0.0      NaN               NaN
                                     1.0      NaN               NaN
(20039.694, 20485.0204]              0.0      NaN               NaN
                                     1.0      NaN               NaN
(20485.0204, 20930.347]              0.0      NaN               NaN
                                     1.0      NaN               NaN
(20930.347, 21375.673]               0.0      NaN               NaN
                                     1.0      NaN               NaN
(21375.673, 21821]                   0.0      1.0               0.0
                                     1.0      NaN               NaN

                                          RevolvingUtilizationOfUnsecuredLines  \
RevolvingUtilizationOfUnsecuredLines dlq
(0, 445.327]                         0.0                               92321.0
                                     1.0                                1746.0
(445.327, 890.653]                   0.0                                  15.0
                                     1.0                                   NaN
(890.653, 1335.98]                   0.0                                  19.0
                                     1.0                                   NaN
(1335.98, 1781.306]                  0.0                                  12.0
                                     1.0                                   NaN
(1781.306, 2226.633]                 0.0                                  12.0
                                     1.0                                   NaN
(2226.633, 2671.959]                 0.0                                   4.0
                                     1.0                                   NaN
(2671.959, 3117.286]                 0.0                                   8.0
                                     1.0                                   NaN
(3117.286, 3562.612]                 0.0                                   9.0
                                     1.0                                   NaN
(3562.612, 4007.939]                 0.0                                   6.0
                                     1.0                                   NaN
(4007.939, 4453.265]                 0.0                                   3.0
                                     1.0                                   1.0
(4453.265, 4898.592]                 0.0                                   4.0
                                     1.0                                   NaN
(4898.592, 5343.918]                 0.0                                   2.0
                                     1.0                                   NaN
(5343.918, 5789.245]                 0.0                                   1.0
                                     1.0                                   NaN
(5789.245, 6234.571]                 0.0                                   1.0
                                     1.0                                   NaN
(6234.571, 6679.898]                 0.0                                   3.0
                                     1.0                                   NaN
...                                                                        ...
(15141.102, 15586.429]               0.0                                   NaN
                                     1.0                                   NaN
(15586.429, 16031.755]               0.0                                   1.0
                                     1.0                                   NaN
(16031.755, 16477.0816]              0.0                                   2.0
                                     1.0                                   NaN
(16477.0816, 16922.408]              0.0                                   NaN
                                     1.0                                   NaN
(16922.408, 17367.735]               0.0                                   NaN
                                     1.0                                   NaN
(17367.735, 17813.0612]              0.0                                   NaN
                                     1.0                                   NaN
(17813.0612, 18258.388]              0.0                                   NaN
                                     1.0                                   NaN
(18258.388, 18703.714]               0.0                                   NaN
                                     1.0                                   NaN
(18703.714, 19149.0408]              0.0                                   NaN
                                     1.0                                   NaN
(19149.0408, 19594.367]              0.0                                   NaN
                                     1.0                                   NaN
(19594.367, 20039.694]               0.0                                   NaN
                                     1.0                                   NaN
(20039.694, 20485.0204]              0.0                                   NaN
                                     1.0                                   NaN
(20485.0204, 20930.347]              0.0                                   NaN
                                     1.0                                   NaN
(20930.347, 21375.673]               0.0                                   NaN
                                     1.0                                   NaN
(21375.673, 21821]                   0.0                                   1.0
                                     1.0                                   NaN

                                              age  \
RevolvingUtilizationOfUnsecuredLines dlq
(0, 445.327]                         0.0  92321.0
                                     1.0   1746.0
(445.327, 890.653]                   0.0     15.0
                                     1.0      NaN
(890.653, 1335.98]                   0.0     19.0
                                     1.0      NaN
(1335.98, 1781.306]                  0.0     12.0
                                     1.0      NaN
(1781.306, 2226.633]                 0.0     12.0
                                     1.0      NaN
(2226.633, 2671.959]                 0.0      4.0
                                     1.0      NaN
(2671.959, 3117.286]                 0.0      8.0
                                     1.0      NaN
(3117.286, 3562.612]                 0.0      9.0
                                     1.0      NaN
(3562.612, 4007.939]                 0.0      6.0
                                     1.0      NaN
(4007.939, 4453.265]                 0.0      3.0
                                     1.0      1.0
(4453.265, 4898.592]                 0.0      4.0
                                     1.0      NaN
(4898.592, 5343.918]                 0.0      2.0
                                     1.0      NaN
(5343.918, 5789.245]                 0.0      1.0
                                     1.0      NaN
(5789.245, 6234.571]                 0.0      1.0
                                     1.0      NaN
(6234.571, 6679.898]                 0.0      3.0
                                     1.0      NaN
...                                           ...
(15141.102, 15586.429]               0.0      NaN
                                     1.0      NaN
(15586.429, 16031.755]               0.0      1.0
                                     1.0      NaN
(16031.755, 16477.0816]              0.0      2.0
                                     1.0      NaN
(16477.0816, 16922.408]              0.0      NaN
                                     1.0      NaN
(16922.408, 17367.735]               0.0      NaN
                                     1.0      NaN
(17367.735, 17813.0612]              0.0      NaN
                                     1.0      NaN
(17813.0612, 18258.388]              0.0      NaN
                                     1.0      NaN
(18258.388, 18703.714]               0.0      NaN
                                     1.0      NaN
(18703.714, 19149.0408]              0.0      NaN
                                     1.0      NaN
(19149.0408, 19594.367]              0.0      NaN
                                     1.0      NaN
(19594.367, 20039.694]               0.0      NaN
                                     1.0      NaN
(20039.694, 20485.0204]              0.0      NaN
                                     1.0      NaN
(20485.0204, 20930.347]              0.0      NaN
                                     1.0      NaN
(20930.347, 21375.673]               0.0      NaN
                                     1.0      NaN
(21375.673, 21821]                   0.0      1.0
                                     1.0      NaN

                                          NumberOfTime30-59DaysPastDueNotWorse  \
RevolvingUtilizationOfUnsecuredLines dlq
(0, 445.327]                         0.0                               92321.0
                                     1.0                                1746.0
(445.327, 890.653]                   0.0                                  15.0
                                     1.0                                   NaN
(890.653, 1335.98]                   0.0                                  19.0
                                     1.0                                   NaN
(1335.98, 1781.306]                  0.0                                  12.0
                                     1.0                                   NaN
(1781.306, 2226.633]                 0.0                                  12.0
                                     1.0                                   NaN
(2226.633, 2671.959]                 0.0                                   4.0
                                     1.0                                   NaN
(2671.959, 3117.286]                 0.0                                   8.0
                                     1.0                                   NaN
(3117.286, 3562.612]                 0.0                                   9.0
                                     1.0                                   NaN
(3562.612, 4007.939]                 0.0                                   6.0
                                     1.0                                   NaN
(4007.939, 4453.265]                 0.0                                   3.0
                                     1.0                                   1.0
(4453.265, 4898.592]                 0.0                                   4.0
                                     1.0                                   NaN
(4898.592, 5343.918]                 0.0                                   2.0
                                     1.0                                   NaN
(5343.918, 5789.245]                 0.0                                   1.0
                                     1.0                                   NaN
(5789.245, 6234.571]                 0.0                                   1.0
                                     1.0                                   NaN
(6234.571, 6679.898]                 0.0                                   3.0
                                     1.0                                   NaN
...                                                                        ...
(15141.102, 15586.429]               0.0                                   NaN
                                     1.0                                   NaN
(15586.429, 16031.755]               0.0                                   1.0
                                     1.0                                   NaN
(16031.755, 16477.0816]              0.0                                   2.0
                                     1.0                                   NaN
(16477.0816, 16922.408]              0.0                                   NaN
                                     1.0                                   NaN
(16922.408, 17367.735]               0.0                                   NaN
                                     1.0                                   NaN
(17367.735, 17813.0612]              0.0                                   NaN
                                     1.0                                   NaN
(17813.0612, 18258.388]              0.0                                   NaN
                                     1.0                                   NaN
(18258.388, 18703.714]               0.0                                   NaN
                                     1.0                                   NaN
(18703.714, 19149.0408]              0.0                                   NaN
                                     1.0                                   NaN
(19149.0408, 19594.367]              0.0                                   NaN
                                     1.0                                   NaN
(19594.367, 20039.694]               0.0                                   NaN
                                     1.0                                   NaN
(20039.694, 20485.0204]              0.0                                   NaN
                                     1.0                                   NaN
(20485.0204, 20930.347]              0.0                                   NaN
                                     1.0                                   NaN
(20930.347, 21375.673]               0.0                                   NaN
                                     1.0                                   NaN
(21375.673, 21821]                   0.0                                   1.0
                                     1.0                                   NaN

                                          DebtRatio  MonthlyIncome  \
RevolvingUtilizationOfUnsecuredLines dlq
(0, 445.327]                         0.0    92321.0        92321.0
                                     1.0     1746.0         1746.0
(445.327, 890.653]                   0.0       15.0           15.0
                                     1.0        NaN            NaN
(890.653, 1335.98]                   0.0       19.0           19.0
                                     1.0        NaN            NaN
(1335.98, 1781.306]                  0.0       12.0           12.0
                                     1.0        NaN            NaN
(1781.306, 2226.633]                 0.0       12.0           12.0
                                     1.0        NaN            NaN
(2226.633, 2671.959]                 0.0        4.0            4.0
                                     1.0        NaN            NaN
(2671.959, 3117.286]                 0.0        8.0            8.0
                                     1.0        NaN            NaN
(3117.286, 3562.612]                 0.0        9.0            9.0
                                     1.0        NaN            NaN
(3562.612, 4007.939]                 0.0        6.0            6.0
                                     1.0        NaN            NaN
(4007.939, 4453.265]                 0.0        3.0            3.0
                                     1.0        1.0            1.0
(4453.265, 4898.592]                 0.0        4.0            4.0
                                     1.0        NaN            NaN
(4898.592, 5343.918]                 0.0        2.0            2.0
                                     1.0        NaN            NaN
(5343.918, 5789.245]                 0.0        1.0            1.0
                                     1.0        NaN            NaN
(5789.245, 6234.571]                 0.0        1.0            1.0
                                     1.0        NaN            NaN
(6234.571, 6679.898]                 0.0        3.0            3.0
                                     1.0        NaN            NaN
...                                             ...            ...
(15141.102, 15586.429]               0.0        NaN            NaN
                                     1.0        NaN            NaN
(15586.429, 16031.755]               0.0        1.0            1.0
                                     1.0        NaN            NaN
(16031.755, 16477.0816]              0.0        2.0            2.0
                                     1.0        NaN            NaN
(16477.0816, 16922.408]              0.0        NaN            NaN

In [85]:

#groupByDependents['age'][0]/groupByDependents['age'][0].sum()
groupByutilization['index'][:,1]
utilization_dlq=groupByutilization['index'][:,1]/(groupByutilization['index'][:,0] + groupByutilization['index'][:,1])

utilization_dlq


utilization_dlq=utilization_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByutilization['index'][:,1].count())

Y=utilization_dlq.as_matrix()
X=Xrange

print Y


import re

_nsre = re.compile('([0-9]+)')
def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower()
            for text in re.split(_nsre, s)]  
keys=utilization_dlq.keys()
print keys
keys=list(keys)
keys.sort(key=natural_sort_key)
print keys

[ 0.01856124  0.25        0.33333333]
Index([u'(0, 445.327]', u'(4007.939, 4453.265]', u'(7570.551, 8015.878]'], dtype='object', name=u'RevolvingUtilizationOfUnsecuredLines')
['(0, 445.327]', '(4007.939, 4453.265]', '(7570.551, 8015.878]']

In [86]:


utilization_dlq=utilization_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByutilization['index'][:,1].count())

Y=utilization_dlq.as_matrix()
X=Xrange

print Y


import re

_nsre = re.compile('([0-9]+)')
def natural_sort_key(s):
    return [int(text) if text.isdigit() else text.lower()
            for text in re.split(_nsre, s)]  
keys=utilization_dlq.keys()
keys=list(keys)
keys.sort(key=natural_sort_key)
print keys



d = {'utilization': keys, 'per': Y}
dfoutput=pd.DataFrame(d,index=None)
dfoutput.to_csv('utilization_per.csv')
dfoutput

#groupByDependents=train_discretized.groupby(['NumberOfDependents', 'SeriousDlqin2yrs']).count()

[ 0.01856124  0.25        0.33333333]
['(0, 445.327]', '(4007.939, 4453.265]', '(7570.551, 8015.878]']

        per           utilization
0  0.018561          (0, 445.327]
1  0.250000  (4007.939, 4453.265]
2  0.333333  (7570.551, 8015.878]

In [73]:
bins = np.linspace(train_discretized.RevolvingUtilizationOfUnsecuredLines.min(), train_discretized.RevolvingUtilizationOfUnsecuredLines.max(),50 )
groupByutilization = train_discretized.groupby([pd.cut(train_discretized.RevolvingUtilizationOfUnsecuredLines, bins),'SeriousDlqin2yrs']).count()

#groupByDependents=train_discretized.groupby(['NumberOfDependents', 'SeriousDlqin2yrs']).count()

In [74]:
#groupByDependents['age'][0]/groupByDependents['age'][0].sum()
groupByutilization['index'][:,1]
utilization_dlq=groupByutilization['index'][:,1]/(groupByutilization['index'][:,0] + groupByutilization['index'][:,1])

In [75]:
utilization_dlq

RevolvingUtilizationOfUnsecuredLines
(0, 1034.857]             0.069779
(1034.857, 2069.714]      0.055556
(2069.714, 3104.571]      0.033333
(3104.571, 4139.429]      0.148148
(4139.429, 5174.286]           NaN
(5174.286, 6209.143]      0.111111
(6209.143, 7244]               NaN
(7244, 8278.857]               NaN
(8278.857, 9313.714]      0.200000
(9313.714, 10348.571]          NaN
(10348.571, 11383.429]         NaN
(11383.429, 12418.286]         NaN
(12418.286, 13453.143]         NaN
(13453.143, 14488]             NaN
(14488, 15522.857]             NaN
(15522.857, 16557.714]         NaN
(16557.714, 17592.571]         NaN
(17592.571, 18627.429]         NaN
(18627.429, 19662.286]         NaN
(19662.286, 20697.143]         NaN
(20697.143, 21732]             NaN
(21732, 22766.857]             NaN
(22766.857, 23801.714]         NaN
(23801.714, 24836.571]         NaN
(24836.571, 25871.429]         NaN
(25871.429, 26906.286]         NaN
(26906.286, 27941.143]         NaN
(27941.143, 28976]             NaN
(28976, 30010.857]             NaN
(30010.857, 31045.714]         NaN
(31045.714, 32080.571]         NaN
(32080.571, 33115.429]         NaN
(33115.429, 34150.286]         NaN
(34150.286, 35185.143]         NaN
(35185.143, 36220]             NaN
(36220, 37254.857]             NaN
(37254.857, 38289.714]         NaN
(38289.714, 39324.571]         NaN
(39324.571, 40359.429]         NaN
(40359.429, 41394.286]         NaN
(41394.286, 42429.143]         NaN
(42429.143, 43464]             NaN
(43464, 44498.857]             NaN
(44498.857, 45533.714]         NaN
(45533.714, 46568.571]         NaN
(46568.571, 47603.429]         NaN
(47603.429, 48638.286]         NaN
(48638.286, 49673.143]         NaN
(49673.143, 50708]             NaN
Name: index, dtype: float64

In [39]:
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np
import plotly
plotly.__version__
import plotly
from plotly.graph_objs import Scatter, Layout
import plotly.plotly as py
import plotly.graph_objs as go
import plotly
# Scientific libraries
from numpy import arange,array,ones
from scipy import stats
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True) 

utilization_dlq=utilization_dlq.dropna()

#-1 as we dont want to take 100
Xrange=np.arange(0,groupByutilization['index'][:,1].count())

Y=utilization_dlq.as_matrix()
X=Xrange

print Y

slope, intercept, r_value, p_value, std_err = stats.linregress(X,Y)
line = slope*X+intercept

trace1 = go.Scatter(
                  x=X, 
                  y=Y, 
                  mode='line',
                  marker=go.Marker(color='rgb((255, 127, 14)'),
                  name='Data'
                  )

trace2 = go.Scatter(
                  x=X, 
                  y=line, 
                  mode='lines',
                  marker=go.Marker(color='rgb(31, 119, 180)'),
                  name='fit'
                  )


annotation = go.Annotation(
                  x=4,
                  y=0.14,
                  text=r_value,
                  showarrow=False,
                  font=go.Font(size=16)
                  )

layout = go.Layout(
                title='Credit Utilization to delinquency',
                plot_bgcolor='rgb(229, 229, 229)',
                  xaxis=go.XAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  yaxis=go.YAxis(zerolinecolor='rgb(255,255,255)', gridcolor='rgb(255,255,255)'),
                  annotations=[annotation]
                )

data = [trace1, trace2]

#print x

#data = [trace]

# Plot and embed in ipython notebook!

fig = go.Figure(data=data, layout=layout)
#fig = go.Figure(data=data)

plotly.offline.iplot(fig, filename='Credit Utilization to delinquency')
print "This is expected as higher the credit utilization, more likely they are to default or late"
print "R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination, "

[ 0.06977949  0.05555556  0.03333333  0.14814815  0.11111111  0.2       ]

This is expected as higher the credit utilization, more likely they are to default or late
R-squared is a statistical measure of how close the data are to the fitted regression line. It is also known as the coefficient of determination,